// import React, { createContext, useState, useContext } from 'react';

// // Translation data for different languages
// const translations = {
//   en: {
// //  title: 'Bored? Study with Games',
//     exploreGeography: 'Explore-Geography',
//     playChemistry: 'Play-Chemistry',
//     learnPhysics: 'Learn-Physics',
//     // science: 'Science Explorer',

//     title: 'Bored? Study with Games',
//     subtitle: 'Learn Smarter, Play Harder!',
//     math: 'Mathematics Quests',
//     wordJourney: 'wordJourney',
//     grammar: 'Grammar Guardians',
//     science: 'Science Explorer',
//     startAdventure: 'Start Your Adventure!',
//     selectLanguage: 'Select Language',
//     leaderboard: 'Leaderboard',
//     home: 'Home',
//     profile: 'Profile',
//     register: 'Register',
//     login: 'Login',
//     name: 'Name:',
//     schoolName: 'School Name:',
//     class: 'Class:',
//     phone: 'Phone Number:',
//     password: 'Password:',
//     haveAccount: 'Already Have An Account?',
//     noAccount: 'Don\'t have an account?',
//     //  title: "Chemistry Match-Up",
//     score: "Score:",
//     time: "Time:",
//     lives: "Lives:",
//     restart: "Restart",
//     hint: "Hint",
//     sound: "Sound",
//     endGameMessage: "Time ran out!",
//     endGameLives: "You've run out of lives!",
//     endGameWin: "🎉 You Won!",
//     endGameLose: "💥 Game Over",
//     playAgain: "Play Again",
//     close: "Close",
//     highScore: "High score:",
//     elementFact: (symbol, name, fact) => `${symbol} — ${name}\n${fact}`,
//     allMatched: (count) => `You matched all ${count} pairs!`,
//       //  title: 'Physics Formula Fill',
//     subtitle: 'Arcade Survival Mode — survive as long as you can ⚡',
//     start: 'Start Game',
//     howToPlay: 'How to Play',
//     levelSelect: 'Level Select',
//     settings: 'Settings',
//     credits: 'Credits',
//     tip: '🔥 Keep streaks going to earn bonus points!',
//     hearts: 'Hearts',
//     time: 'Time',
//     // score: 'Score',
//     streak: 'Streak',
//     hint: 'Hint',
//     pause: 'Pause',
//     resume: 'Resume',
//     topScore: 'Top Score:',
//     selectTerm: 'Select the missing term',
//     gameOver: '🎮 Game Over',
//     finalScore: 'Final Score',
//     playAgain: 'Play Again',
//     mainMenu: 'Main Menu',
//     shareScore: 'Share Score',
//     youSurvived: (time) => `⏳ You survived ${time}s`,
//     newHighScore: '🏆 New high score! Congratulations!',
//     keepPracticing: 'Keep practicing to beat your high score!',
//      askMe: 'Ask me',
//     profile: 'Profile',
//     coursest: 'Courses',
//     howToPlayContent: [
//       'Start with 3 hearts and 60s.',
//       'Correct → +10 pts, +3s, builds streaks. Wrong → lose heart & -5s.',
//       '2 hints per run: removes one wrong option (-5 pts each).',
//       'Survive as long as you can. Top scores saved locally.'
//     ]
  
//   },
//   hi: {
//      exploreGeography: 'भूगोल खोजें',
//     playChemistry: 'रसायन विज्ञान खेलें',
//     learnPhysics: 'भौतिकी सीखें',
//     title: 'ऊब गए हैं? खेलों से पढ़ाई करें',
//     subtitle: 'स्मार्ट सीखें, और जोर से खेलें!',
//     math: 'गणित खोज',
//     wordJourney: 'शब्द यात्रा',
//     grammar: 'व्याकरण रक्षक',
//     science: 'विज्ञान अन्वेषक',
//     startAdventure: 'अपना साहसिक कार्य शुरू करें!',
//     selectLanguage: 'भाषा चुनें',
//     leaderboard: 'लीडरबोर्ड',
//     home: 'होम',
//     profile: 'प्रोफ़ाइल',
//     register: 'रजिस्टर',
//     login: 'लॉग इन करें',
//     name: 'नाम:',
//     schoolName: 'विद्यालय का नाम:',
//     class: 'कक्षा:',
    
//     phone: 'फ़ोन नंबर:',
//     password: 'पासवर्ड:',
//     haveAccount: 'पहले से ही एक खाता है?',
//     noAccount: 'खाता नहीं है?',
//      title: "रसायन विज्ञान मिलाप",
//     score: "अंक:",
//     time: "समय:",
//     lives: "जीवन:",
//     restart: "पुनः प्रारंभ करें",
//     hint: "संकेत",
//     sound: "ध्वनि",
//     endGameMessage: "समय समाप्त!",
//     endGameLives: "आपके जीवन समाप्त हो गए हैं!",
//     endGameWin: "🎉 आप जीत गए!",
//     endGameLose: "💥 खेल समाप्त",
//     playAgain: "फिर से खेलें",
//     close: "बंद करें",
//     highScore: "उच्चतम स्कोर:",
//     elementFact: (symbol, name, fact) => `${symbol} — ${name}\n${fact}`,
//     allMatched: (count) => `आपने सभी ${count} जोड़े मिलाए!`,
//   // title: 'भौतिक विज्ञान सूत्र भरें',
//     subtitle: 'आर्केड सर्वाइवल मोड — जब तक आप कर सकते हैं तब तक जीवित रहें ⚡',
//     start: 'खेल शुरू करें',
//     howToPlay: 'कैसे खेलें',
//     levelSelect: 'स्तर चुनें',
//     settings: 'सेटिंग्स',
//     credits: 'क्रेडिट',
//     tip: '🔥 बोनस अंक अर्जित करने के लिए लकीरें जारी रखें!',
//     hearts: 'दिल',
//     time: 'समय',
//     score: 'अंक',
//     streak: 'लकीर',
//     hint: 'संकेत',
//     pause: 'रोकें',
//     resume: 'फिर से शुरू करें',
//     topScore: 'उच्चतम स्कोर:',
//     selectTerm: 'लुप्त पद का चयन करें',
//     gameOver: '🎮 खेल समाप्त',
//     finalScore: 'अंतिम अंक',
//     playAgain: 'फिर से खेलें',
//     mainMenu: 'मुख्य मेनू',
//     shareScore: 'अंक साझा करें',
//     youSurvived: (time) => `⏳ आप ${time}s तक जीवित रहे`,
//     newHighScore: '🏆 नया उच्च स्कोर! बधाई हो!',
//     keepPracticing: 'अपना उच्च स्कोर हराने के लिए अभ्यास करते रहें!',
//       // leaderboard: 'Leaderboard',
//     // home: 'Home',
//     askMe: 'मुझसे पूछें',
//     profile: 'प्रोफ़ाइल',
//     coursest: 'पाठ्यक्रम',
//     howToPlayContent: [
//       '3 दिलों और 60s के साथ शुरू करें।',
//       'सही → +10 अंक, +3s, लकीरें बनाता है। गलत → दिल खोना और -5s।',
//       'प्रति दौड़ 2 संकेत: एक गलत विकल्प हटाता है (-5 अंक प्रत्येक)।',
//       'जब तक आप कर सकते हैं तब तक जीवित रहें। शीर्ष स्कोर स्थानीय रूप से सहेजे गए।'
//     ]


//   },
//   or: {
//     title: 'ବୋର ହେଉଛନ୍ତି? ଖେଳ ସହିତ ପଢନ୍ତୁ',
//   exploreGeography: 'ଭୂଗୋଳ ଅନୁସନ୍ଧାନ କରନ୍ତୁ',
//     playChemistry: 'ରସାୟନ ବିଜ୍ଞାନ ଖେଳନ୍ତୁ',
//     learnPhysics: 'ପଦାର୍ଥ ବିଜ୍ଞାନ ଶିଖନ୍ତୁ',

//     subtitle: 'ସ୍ମାର୍ଟ ଶିଖନ୍ତୁ, ହାର୍ଡ ଖେଳନ୍ତୁ!',
//     math: 'ଗଣିତ କ୍ୱେଷ୍ଟ୍',
//     wordJourney: 'ଶବ୍ଦ ଯାତ୍ରା',
//     grammar: 'ବ୍ୟାକରଣ ଗାର୍ଡିଆନ୍',
//     science: 'ବିଜ୍ଞାନ ଏକ୍ସପ୍ଲୋରର୍',
//     startAdventure: 'ଆପଣଙ୍କର ଦୁଃସାହସ ଆରମ୍ଭ କରନ୍ତୁ!',
//     selectLanguage: 'ଭାଷା ବାଛନ୍ତୁ',
//     leaderboard: 'ଲିଡରବୋର୍ଡ',
//     home: 'ହୋମ୍',
//     profile: 'ପ୍ରୋଫାଇଲ୍',
//     register: 'ରେଜିଷ୍ଟର୍',
//     login: 'ଲଗଇନ୍ କରନ୍ତୁ',
//     name: 'ନାମ:',
//     schoolName: 'ବିଦ୍ୟାଳୟର ନାମ:',
//     class: 'ଶ୍ରେଣୀ:',
//     phone: 'ଫୋନ ନମ୍ବର:',
//     password: 'ପାସୱାର୍ଡ:',
//     haveAccount: 'ଆଗରୁ ଖାତା ଅଛି?',
//     noAccount: 'ଖାତା ନାହିଁ?',

// //  title: "ରସାୟନ ବିଜ୍ଞାନ ମେଳାଣ",
//     score: "ସ୍କୋର:",
//     time: "ସମୟ:",
//     lives: "ଜୀବନ:",
//     restart: "ପୁନଃ ଆରମ୍ଭ",
//     hint: "ସଙ୍କେତ",
//     sound: "ଶବ୍ଦ",
//     endGameMessage: "ସମୟ ସରିଗଲା!",
//     endGameLives: "ଆପଣଙ୍କ ଜୀବନ ସରିଗଲା!",
//     endGameWin: "🎉 ଆପଣ ଜିତିଲେ!",
//     endGameLose: "💥 ଖେଳ ଶେଷ",
//     playAgain: "ପୁଣି ଖେଳନ୍ତୁ",
//     close: "ବନ୍ଦ କରନ୍ତୁ",
//     highScore: "ସର୍ବୋଚ୍ଚ ସ୍କୋର:",
//     elementFact: (symbol, name, fact) => `${symbol} — ${name}\n${fact}`,
//     allMatched: (count) => `ଆପଣ ସମସ୍ତ ${count} ଯୋଡ଼ି ମିଶାଇଲେ!`,
//      title: 'ପଦାର୍ଥ ବିଜ୍ଞାନ ସୂତ୍ର ପୂରଣ',
//     subtitle: 'ଆର୍କେଡ୍ ସର୍ଭାଇଭାଲ୍ ମୋଡ୍ — ଯେତେ ସମୟ ପର୍ଯ୍ୟନ୍ତ ବଞ୍ଚିପାରିବେ ବଞ୍ଚନ୍ତୁ ⚡',
//     start: 'ଖେଳ ଆରମ୍ଭ କରନ୍ତୁ',
//     howToPlay: 'କିପରି ଖେଳିବେ',
//     levelSelect: 'ସ୍ତର ବାଛନ୍ତୁ',
//     settings: 'ସେଟିଙ୍ଗ୍ସ',
//     credits: 'କ୍ରେଡିଟ୍',
//     tip: '🔥 ବୋନସ୍ ପଏଣ୍ଟ ପାଇବା ପାଇଁ ଷ୍ଟ୍ରିକ୍ ଜାରି ରଖନ୍ତୁ!',
//     hearts: 'ହୃଦୟ',
//     // time: 'ସମୟ',
//     // score: 'ସ୍କୋର',
//     streak: 'ଷ୍ଟ୍ରିକ୍',
//     // hint: 'ସୂଚନା',
//     pause: 'ବିରତି',
//     resume: 'ପୁନରାମ୍ଭ',
//     topScore: 'ସର୍ବୋଚ୍ଚ ସ୍କୋର:',
//     selectTerm: 'ନିଖୋଜ ଶବ୍ଦ ବାଛନ୍ତୁ',
//     gameOver: '🎮 ଖେଳ ଶେଷ',
//     finalScore: 'ଅନ୍ତିମ ସ୍କୋର',
//     // playAgain: 'ପୁନଃ ଖେଳନ୍ତୁ',
//     mainMenu: 'ମୁଖ୍ୟ ମେନୁ',
//     shareScore: 'ସ୍କୋର ସେୟାର କରନ୍ତୁ',
//     youSurvived: (time) => `⏳ ଆପଣ ${time}s ପର୍ଯ୍ୟନ୍ତ ବଞ୍ଚିଲେ`,
//     newHighScore: '🏆 ନୂଆ ସର୍ବୋଚ୍ଚ ସ୍କୋର! ଅଭିନନ୍ଦନ!',
//     keepPracticing: 'ଆପଣଙ୍କର ସର୍ବୋଚ୍ଚ ସ୍କୋରକୁ ହରାଇବା ପାଇଁ ଅଭ୍ୟାସ କରନ୍ତୁ!',
//     // leaderboard: 'लीडरबोर्ड',
//     // home: 'होम',
   
//       // leaderboard: 'ଲିଡରବୋର୍ଡ',
//     // home: 'ହୋମ୍',
//     askMe: 'ମୋତେ ପଚାରନ୍ତୁ',
//     // profile: 'ପ୍ରୋଫାଇଲ୍',
//     coursest: 'ପାଠ୍ୟକ୍ରମ',
//     howToPlayContent: [
//       '3 ହୃଦୟ ଏବଂ 60s ସହିତ ଆରମ୍ଭ କରନ୍ତୁ।',
//       'ଠିକ୍ → +10 ପଏଣ୍ଟ୍, +3s, ଷ୍ଟ୍ରିକ୍ସ ତିଆରି କରେ। ଭୁଲ୍ → ହୃଦୟ ହରାଇବା ଏବଂ -5s।',
//       'ପ୍ରତି ରନ୍‌ରେ 2 ସୂଚନା: ଏକ ଭୁଲ୍ ବିକଳ୍ପ ହଟାଇଥାଏ (-5 ପଏଣ୍ଟ୍ ପ୍ରତ୍ୟେକ)।',
//       'ଯେତେ ସମୟ ପର୍ଯ୍ୟନ୍ତ ବଞ୍ଚିପାରିବେ ବଞ୍ଚନ୍ତୁ। ସର୍ବୋଚ୍ଚ ସ୍କୋର ସ୍ଥାନୀୟ ଭାବରେ ସେଭ୍ ହୋଇଥାଏ।'
//     ]

//   },
// };

// const LanguageContext = createContext();

// export const LanguageProvider = ({ children }) => {
//   const [language, setLanguage] = useState('en');

//   const value = {
//     language,
//     setLanguage,
//     translations: translations[language],
//   };

//   return (
//     <LanguageContext.Provider value={value}>
//       {children}
//     </LanguageContext.Provider>
//   );
// };

// export const useLanguage = () => useContext(LanguageContext);





import React, { createContext, useState, useContext } from 'react';

// Translation data for different languages
const translations = {
  en: {
    exploreGeography: 'Explore-Geography',
    playChemistry: 'Play-Chemistry',
    learnPhysics: 'Learn-Physics',
    // science: 'Science Explorer',

    title: 'Bored? Study with Games',
    // subtitle: 'Learn Smarter, Play Harder!',
    math: 'Mathematics Quests',
    wordJourney: 'wordJourney',
    grammar: 'Grammar Guardians',
    science: 'Science Explorer',
    startAdventure: 'Start Your Adventure!',
    selectLanguage: 'Select Language',
    leaderboard: 'Leaderboard',
    home: 'Home',
    profile: 'Profile',
    register: 'Register',
    login: 'Login',
    name: 'Name:',
    schoolName: 'School Name:',
    class: 'Class:',
    phone: 'Phone Number:',
    password: 'Password:',
    haveAccount: 'Already Have An Account?',
    noAccount: 'Don\'t have an account?',
    // title: "Chemistry Match-Up",
    score: "Score:",
    time: "Time:",
    lives: "Lives:",
    restart: "Restart",
    hint: "Hint",
    sound: "Sound",
    endGameMessage: "Time ran out!",
    endGameLives: "You've run out of lives!",
    endGameWin: "🎉 You Won!",
    endGameLose: "💥 Game Over",
    playAgain: "Play Again",
    close: "Close",
    highScore: "High score:",
    elementFact: (symbol, name, fact) => `${symbol} — ${name}\n${fact}`,
    allMatched: (count) => `You matched all ${count} pairs!`,
    // title: 'Physics Formula Fill',
    subtitle: 'Arcade Survival Mode — survive as long as you can ⚡',
    start: 'Start Game',
    howToPlay: 'How to Play',
    levelSelect: 'Level Select',
    settings: 'Settings',
    credits: 'Credits',
    tip: '🔥 Keep streaks going to earn bonus points!',
    hearts: 'Hearts',
    // time: 'Time',
    // score: 'Score',
    streak: 'Streak',
    // hint: 'Hint',
    pause: 'Pause',
    resume: 'Resume',
    topScore: 'Top Score:',
    selectTerm: 'Select the missing term',
    gameOver: '🎮 Game Over',
    finalScore: 'Final Score',
    // playAgain: 'Play Again',
    mainMenu: 'Main Menu',
    shareScore: 'Share Score',
    youSurvived: (time) => `⏳ You survived ${time}s`,
    newHighScore: '🏆 New high score! Congratulations!',
    keepPracticing: 'Keep practicing to beat your high score!',
    askMe: 'Ask me',
    // profile: 'Profile',
    coursest: 'Courses',
    howToPlayContent: [
      'Start with 3 hearts and 60s.',
      'Correct → +10 pts, +3s, builds streaks. Wrong → lose heart & -5s.',
      '2 hints per run: removes one wrong option (-5 pts each).',
      'Survive as long as you can. Top scores saved locally.'
    ]
  },

  hi: {
    exploreGeography: 'भूगोल खोजें',
    playChemistry: 'रसायन विज्ञान खेलें',
    learnPhysics: 'भौतिकी सीखें',
    title: 'ऊब गए हैं? खेलों से पढ़ाई करें',
    subtitle: 'स्मार्ट सीखें, और जोर से खेलें!',
    math: 'गणित खोज',
    wordJourney: 'शब्द यात्रा',
    grammar: 'व्याकरण रक्षक',
    science: 'विज्ञान अन्वेषक',
    startAdventure: 'अपना साहसिक कार्य शुरू करें!',
    selectLanguage: 'भाषा चुनें',
    leaderboard: 'लीडरबोर्ड',
    home: 'होम',
    profile: 'प्रोफ़ाइल',
    register: 'रजिस्टर',
    login: 'लॉग इन करें',
    name: 'नाम:',
    schoolName: 'विद्यालय का नाम:',
    class: 'कक्षा:',
    phone: 'फ़ोन नंबर:',
    password: 'पासवर्ड:',
    haveAccount: 'पहले से ही एक खाता है?',
    noAccount: 'खाता नहीं है?',
    // title: "रसायन विज्ञान मिलाप",
    score: "अंक:",
    time: "समय:",
    lives: "जीवन:",
    restart: "पुनः प्रारंभ करें",
    hint: "संकेत",
    sound: "ध्वनि",
    endGameMessage: "समय समाप्त!",
    endGameLives: "आपके जीवन समाप्त हो गए हैं!",
    endGameWin: "🎉 आप जीत गए!",
    endGameLose: "💥 खेल समाप्त",
    playAgain: "फिर से खेलें",
    close: "बंद करें",
    highScore: "उच्चतम स्कोर:",
    elementFact: (symbol, name, fact) => `${symbol} — ${name}\n${fact}`,
    allMatched: (count) => `आपने सभी ${count} जोड़े मिलाए!`,
    // title: 'भौतिक विज्ञान सूत्र भरें',
    // subtitle: 'आर्केड सर्वाइवल मोड — जब तक आप कर सकते हैं तब तक जीवित रहें ⚡',
    start: 'खेल शुरू करें',
    howToPlay: 'कैसे खेलें',
    levelSelect: 'स्तर चुनें',
    settings: 'सेटिंग्स',
    credits: 'क्रेडिट',
    tip: '🔥 बोनस अंक अर्जित करने के लिए लकीरें जारी रखें!',
    hearts: 'दिल',
    // time: 'समय',
    // score: 'अंक',
    streak: 'लकीर',
    // hint: 'संकेत',
    pause: 'रोकें',
    resume: 'फिर से शुरू करें',
    topScore: 'उच्चतम स्कोर:',
    selectTerm: 'लुप्त पद का चयन करें',
    gameOver: '🎮 खेल समाप्त',
    finalScore: 'अंतिम अंक',
    // playAgain: 'फिर से खेलें',
    mainMenu: 'मुख्य मेनू',
    shareScore: 'अंक साझा करें',
    youSurvived: (time) => `⏳ आप ${time}s तक जीवित रहे`,
    newHighScore: '🏆 नया उच्च स्कोर! बधाई हो!',
    keepPracticing: 'अपना उच्च स्कोर हराने के लिए अभ्यास करते रहें!',
    askMe: 'मुझसे पूछें',
    // profile: 'प्रोफ़ाइल',
    coursest: 'पाठ्यक्रम',
    howToPlayContent: [
      '3 दिलों और 60s के साथ शुरू करें।',
      'सही → +10 अंक, +3s, लकीरें बनाता है। गलत → दिल खोना और -5s।',
      'प्रति दौड़ 2 संकेत: एक गलत विकल्प हटाता है (-5 अंक प्रत्येक)।',
      'जब तक आप कर सकते हैं तब तक जीवित रहें। शीर्ष स्कोर स्थानीय रूप से सहेजे गए।'
    ]
  },

  or: {
    title: 'ବୋର ହେଉଛନ୍ତି? ଖେଳ ସହିତ ପଢନ୍ତୁ',
    exploreGeography: 'ଭୂଗୋଳ ଅନୁସନ୍ଧାନ କରନ୍ତୁ',
    playChemistry: 'ରସାୟନ ବିଜ୍ଞାନ ଖେଳନ୍ତୁ',
    learnPhysics: 'ପଦାର୍ଥ ବିଜ୍ଞାନ ଶିଖନ୍ତୁ',
    subtitle: 'ସ୍ମାର୍ଟ ଶିଖନ୍ତୁ, ହାର୍ଡ ଖେଳନ୍ତୁ!',
    math: 'ଗଣିତ କ୍ୱେଷ୍ଟ୍',
    wordJourney: 'ଶବ୍ଦ ଯାତ୍ରା',
    grammar: 'ବ୍ୟାକରଣ ଗାର୍ଡିଆନ୍',
    science: 'ବିଜ୍ଞାନ ଏକ୍ସପ୍ଲୋରର୍',
    startAdventure: 'ଆପଣଙ୍କର ଦୁଃସାହସ ଆରମ୍ଭ କରନ୍ତୁ!',
    selectLanguage: 'ଭାଷା ବାଛନ୍ତୁ',
    leaderboard: 'ଲିଡରବୋର୍ଡ',
    home: 'ହୋମ୍',
    profile: 'ପ୍ରୋଫାଇଲ୍',
    register: 'ରେଜିଷ୍ଟର୍',
    login: 'ଲଗଇନ୍ କରନ୍ତୁ',
    name: 'ନାମ:',
    schoolName: 'ବିଦ୍ୟାଳୟର ନାମ:',
    class: 'ଶ୍ରେଣୀ:',
    phone: 'ଫୋନ ନମ୍ବର:',
    password: 'ପାସୱାର୍ଡ:',
    haveAccount: 'ଆଗରୁ ଖାତା ଅଛି?',
    noAccount: 'ଖାତା ନାହିଁ?',
    // title: "ରସାୟନ ବିଜ୍ଞାନ ମେଳାଣ",
    score: "ସ୍କୋର:",
    time: "ସମୟ:",
    lives: "ଜୀବନ:",
    restart: "ପୁନଃ ଆରମ୍ଭ",
    hint: "ସଙ୍କେତ",
    sound: "ଶବ୍ଦ",
    endGameMessage: "ସମୟ ସରିଗଲା!",
    endGameLives: "ଆପଣଙ୍କ ଜୀବନ ସରିଗଲା!",
    endGameWin: "🎉 ଆପଣ ଜିତିଲେ!",
    endGameLose: "💥 ଖେଳ ଶେଷ",
    playAgain: "ପୁଣି ଖେଳନ୍ତୁ",
    close: "ବନ୍ଦ କରନ୍ତୁ",
    highScore: "ସର୍ବୋଚ୍ଚ ସ୍କୋର:",
    elementFact: (symbol, name, fact) => `${symbol} — ${name}\n${fact}`,
    allMatched: (count) => `ଆପଣ ସମସ୍ତ ${count} ଯୋଡ଼ି ମିଶାଇଲେ!`,
    // title: 'ପଦାର୍ଥ ବିଜ୍ଞାନ ସୂତ୍ର ପୂରଣ',
    // subtitle: 'ଆର୍କେଡ୍ ସର୍ଭାଇଭାଲ୍ ମୋଡ୍ — ଯେତେ ସମୟ ପର୍ଯ୍ୟନ୍ତ ବଞ୍ଚିପାରିବେ ବଞ୍ଚନ୍ତୁ ⚡',
    start: 'ଖେଳ ଆରମ୍ଭ କରନ୍ତୁ',
    howToPlay: 'କିପରି ଖେଳିବେ',
    levelSelect: 'ସ୍ତର ବାଛନ୍ତୁ',
    settings: 'ସେଟିଙ୍ଗ୍ସ',
    credits: 'କ୍ରେଡିଟ୍',
    tip: '🔥 ବୋନସ୍ ପଏଣ୍ଟ ପାଇବା ପାଇଁ ଷ୍ଟ୍ରିକ୍ ଜାରି ରଖନ୍ତୁ!',
    hearts: 'ହୃଦୟ',
    // time: 'ସମୟ',
    // score: 'ସ୍କୋର',
    streak: 'ଷ୍ଟ୍ରିକ୍',
    // hint: 'ସୂଚନା',
    pause: 'ବିରତି',
    resume: 'ପୁନରାମ୍ଭ',
    topScore: 'ସର୍ବୋଚ୍ଚ ସ୍କୋର:',
    selectTerm: 'ନିଖୋଜ ଶବ୍ଦ ବାଛନ୍ତୁ',
    gameOver: '🎮 ଖେଳ ଶେଷ',
    finalScore: 'ଅନ୍ତିମ ସ୍କୋର',
    // playAgain: 'ପୁନଃ ଖେଳନ୍ତୁ',
    mainMenu: 'ମୁଖ୍ୟ ମେନୁ',
    shareScore: 'ସ୍କୋର ସେୟାର କରନ୍ତୁ',
    youSurvived: (time) => `⏳ ଆପଣ ${time}s ପର୍ଯ୍ୟନ୍ତ ବଞ୍ଚିଲେ`,
    newHighScore: '🏆 ନୂଆ ସର୍ବୋଚ୍ଚ ସ୍କୋର! ଅଭିନନ୍ଦନ!',
    keepPracticing: 'ଆପଣଙ୍କର ସର୍ବୋଚ୍ଚ ସ୍କୋରକୁ ହରାଇବା ପାଇଁ ଅଭ୍ୟାସ କରନ୍ତୁ!',
    askMe: 'ମୋତେ ପଚାରନ୍ତୁ',
    // profile: 'ପ୍ରୋଫାଇଲ୍',
    coursest: 'ପାଠ୍ୟକ୍ରମ',
    howToPlayContent: [
      '3 ହୃଦୟ ଏବଂ 60s ସହିତ ଆରମ୍ଭ କରନ୍ତୁ।',
      'ଠିକ୍ → +10 ପଏଣ୍ଟ୍, +3s, ଷ୍ଟ୍ରିକ୍ସ ତିଆରି କରେ। ଭୁଲ୍ → ହୃଦୟ ହରାଇବା ଏବଂ -5s।',
      'ପ୍ରତି ରନ୍‌ରେ 2 ସୂଚନା: ଏକ ଭୁଲ୍ ବିକଳ୍ପ ହଟାଇଥାଏ (-5 ପଏଣ୍ଟ୍ ପ୍ରତ୍ୟେକ)।',
      'ଯେତେ ସମୟ ପର୍ଯ୍ୟନ୍ତ ବଞ୍ଚିପାରିବେ ବଞ୍ଚନ୍ତୁ। ସର୍ବୋଚ୍ଚ ସ୍କୋର ସ୍ଥାନୀୟ ଭାବରେ ସେଭ୍ ହୋଇଥାଏ।'
    ]
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const value = {
    language,
    setLanguage,
    translations: translations[language],
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
